// <auto-generated />
using System;
using DALTWNC_QUIZ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DALTWNC_QUIZ.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114040041_AllowNullSelectedChoiceID")]
    partial class AllowNullSelectedChoiceID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoiceID"), 1L, 1);

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("ChoiceID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Choice");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("QuizID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"), 1L, 1);

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CustomerID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"), 1L, 1);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuestionCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryID");

                    b.ToTable("QuestionCategory");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Quiz", b =>
                {
                    b.Property<int>("QuizID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizID"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("QuizTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("QuizID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SubjectID");

                    b.ToTable("Quiz");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuizAttempt", b =>
                {
                    b.Property<int>("QuizAttemptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuizAttemptID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptID"), 1L, 1);

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMinute")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartTime");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizAttempts", (string)null);
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuizAttemptQuestion", b =>
                {
                    b.Property<int>("QuizAttemptQuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuizAttemptQuestionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizAttemptQuestionID"), 1L, 1);

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<int>("QuizAttemptID")
                        .HasColumnType("int")
                        .HasColumnName("QuizAttemptID");

                    b.Property<int?>("SelectedChoiceID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("QuizAttemptQuestionID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("QuizAttemptID");

                    b.HasIndex("SelectedChoiceID");

                    b.ToTable("QuizAttemptQuestions", (string)null);
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuizQuestion", b =>
                {
                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("QuizID", "QuestionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Rating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("RatingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("QuizID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.SavedQuiz", b =>
                {
                    b.Property<int>("SavedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedID"), 1L, 1);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("QuizID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SavedID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("QuizID");

                    b.ToTable("SavedQuiz");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectID"), 1L, 1);

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SubjectID");

                    b.HasIndex("ParentID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Username");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Choice", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Comment", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALTWNC_QUIZ.Models.Quiz", "Quiz")
                        .WithMany("Comments")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Customer", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("DALTWNC_QUIZ.Models.Customer", "Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Question", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.QuestionCategory", "QuestionCategory")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryID");

                    b.HasOne("DALTWNC_QUIZ.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionCategory");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Quiz", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.User", "User")
                        .WithMany("Quizzes")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALTWNC_QUIZ.Models.Subject", "Subject")
                        .WithMany("Quizzes")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuizAttempt", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Customer", "Customer")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizAttempt_Customer");

                    b.HasOne("DALTWNC_QUIZ.Models.Quiz", "Quiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuizAttempt_Quiz");

                    b.Navigation("Customer");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuizAttemptQuestion", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptQuestions_Questions");

                    b.HasOne("DALTWNC_QUIZ.Models.QuizAttempt", "QuizAttempt")
                        .WithMany("QuizAttemptQuestions")
                        .HasForeignKey("QuizAttemptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptQuestions_Attempts");

                    b.HasOne("DALTWNC_QUIZ.Models.Choice", "SelectedChoice")
                        .WithMany()
                        .HasForeignKey("SelectedChoiceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AttemptQuestions_Choices");

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");

                    b.Navigation("SelectedChoice");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuizQuestion", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Question", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALTWNC_QUIZ.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Rating", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Customer", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALTWNC_QUIZ.Models.Quiz", "Quiz")
                        .WithMany("Ratings")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.SavedQuiz", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Customer", "Customer")
                        .WithMany("SavedQuizzes")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALTWNC_QUIZ.Models.Quiz", "Quiz")
                        .WithMany("SavedQuizzes")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Subject", b =>
                {
                    b.HasOne("DALTWNC_QUIZ.Models.Subject", "ParentSubject")
                        .WithMany("ChildSubjects")
                        .HasForeignKey("ParentID");

                    b.Navigation("ParentSubject");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Customer", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("QuizAttempts");

                    b.Navigation("Ratings");

                    b.Navigation("SavedQuizzes");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Question", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuestionCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Quiz", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("QuizAttempts");

                    b.Navigation("QuizQuestions");

                    b.Navigation("Ratings");

                    b.Navigation("SavedQuizzes");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.QuizAttempt", b =>
                {
                    b.Navigation("QuizAttemptQuestions");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.Subject", b =>
                {
                    b.Navigation("ChildSubjects");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("DALTWNC_QUIZ.Models.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Quizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
